version: '3.8'
networks:
  rabbitmq-network:
    external: true

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbitmq-network
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  notification-service:
    build: .
    container_name: notification-service
    ports:
      - "${WEBSOCKET_PORT}:${WEBSOCKET_PORT}"
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq-network
    environment:
      RABBITMQ_URL: ${RABBITMQ_URL}
      EMAIL_SERVICE: ${EMAIL_SERVICE}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
      WEBSOCKET_PORT: ${WEBSOCKET_PORT}
